"""Authentication helpers (TOTP, passwords, recovery codes, sessions, lockout).

Exposes the TOTP primitives, password-hash helpers, session-cookie helpers,
signed session/challenge token helpers, and the auth state / lockout / recovery
helpers moved out of ``synology-monitor.py``.
"""

from .totp import (
    _build_totp_uri,
    _generate_totp_secret,
    _totp_available,
    _totp_code_at,
    _verify_totp_token,
)
from .password import (
    generate_password_hash,
    check_password_hash,
)
from .cookies import (
    AUTH_COOKIE_NAME,
    AUTH_CHALLENGE_COOKIE_NAME,
    AUTH_SESSION_TTL_SEC,
    AUTH_CHALLENGE_TTL_SEC,
    build_cookie_header,
    clear_cookie_header,
    parse_cookie_header,
)
from .sessions import (
    issue_session_token,
    issue_challenge_token,
    session_token_valid,
    challenge_token_valid,
)
from .auth_state import (
    configure,
    get_auth_state_path,
    _default_auth_state,
    _load_auth_state,
    _save_auth_state,
    _hash_recovery_code,
    _generate_recovery_codes,
    _issue_recovery_hashes,
    _build_qr_data_uri,
    _purge_pending_setups,
    _create_pending_setup,
    _get_pending_setup,
    _pop_pending_setup,
    _is_locked,
    _register_auth_failure,
    _format_lock_wait,
    _lockout_message,
    _invalid_password_message,
    _register_auth_success,
    _sign_payload,
    _verify_signed_payload,
    _auth_initialized,
    _consume_recovery_code,
    _count_unused_recovery,
)

__all__ = [
    "_build_totp_uri",
    "_generate_totp_secret",
    "_totp_available",
    "_totp_code_at",
    "_verify_totp_token",
    "generate_password_hash",
    "check_password_hash",
    "AUTH_COOKIE_NAME",
    "AUTH_CHALLENGE_COOKIE_NAME",
    "AUTH_SESSION_TTL_SEC",
    "AUTH_CHALLENGE_TTL_SEC",
    "build_cookie_header",
    "clear_cookie_header",
    "parse_cookie_header",
    "issue_session_token",
    "issue_challenge_token",
    "session_token_valid",
    "challenge_token_valid",
    "configure",
    "get_auth_state_path",
    "_default_auth_state",
    "_load_auth_state",
    "_save_auth_state",
    "_hash_recovery_code",
    "_generate_recovery_codes",
    "_issue_recovery_hashes",
    "_build_qr_data_uri",
    "_purge_pending_setups",
    "_create_pending_setup",
    "_get_pending_setup",
    "_pop_pending_setup",
    "_is_locked",
    "_register_auth_failure",
    "_format_lock_wait",
    "_lockout_message",
    "_invalid_password_message",
    "_register_auth_success",
    "_sign_payload",
    "_verify_signed_payload",
    "_auth_initialized",
    "_consume_recovery_code",
    "_count_unused_recovery",
]
